# Generated by Django 6.0.7 on 2026-07-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название должности")),
                ("description", models.TextField(verbose_name="Описание должности")),
            ],
            options={
                "verbose_name": "Должность",
                "verbose_name_plural": "Должности",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Quest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=200, unique=True, verbose_name="Формулировка задачи")),
                ("description", models.TextField(verbose_name="Описание задачи")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("dead_line", models.DateTimeField(null=True, verbose_name="Дата создания")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("1_created", "Создана"),
                            ("2_processing", "Обрабатывается"),
                            ("3_failed", "Не выполнена"),
                            ("4_expired", "Просрочена"),
                            ("5_cancelled", "Отменена"),
                            ("6_success", "Успешно завершена"),
                        ],
                        default="created",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                ("report", models.TextField(blank=True, null=True, verbose_name="Отчет")),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["required", "status", "title"],
            },
        ),
    ]
