# Generated by Django 6.0.7 on 2026-07-29 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="operator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Ответственный исполнитель",
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="related_quest",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_quests",
                to="management.quest",
                verbose_name="Задача-родитель",
            ),
        ),
        migrations.AddField(
            model_name="quest",
            name="required",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="responsibilities",
                to="management.activity",
                verbose_name="Ответственная должность",
            ),
        ),
    ]
