# Generated by Django 6.0.7 on 2026-08-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quest",
            name="report",
            field=models.TextField(blank=True, default="", verbose_name="Отчет"),
        ),
    ]
