# Generated by Django 6.0.7 on 2026-08-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_quest_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="partners",
            field=models.ManyToManyField(to="management.activity", verbose_name="Контактирующие должности"),
        ),
    ]
